apiVersion: v1
kind: Service
metadata:
  name: {{ include "example-app.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "example-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default .Values.service.port }}
      protocol: TCP
      name: {{ .Values.service.name | default "default" }}
  selector:
    {{- include "example-app.selectorLabels" . | nindent 4 }}
